version: '2'
services:
  gearman:
    extends:
      file: ./docker-compose.common.yml
      service: gearman

  gearman-worker:
    extends:
      file: ./docker-compose.common.yml
      service: gearman-worker
    volumes_from:
      - web
    depends_on:
      - gearman
    dns: 84.89.128.11

  nginx:
    build: ./docker/nginx/
    ports:
      - "8000:80"
    volumes_from:
      - web

  web:
    build: .
    environment:
      DATABASE_URL: "postgres://simannotator:2Fi4l57HR+sWTVSu6BUfREXaHPI2vxjyIIbulzOaEdk=@asplab-db.s.upf.edu/simannotator"
      DEPLOY_ENV: "prod"
    volumes:
      - /static/
      - /mnt/asplab-web/asplab-shared/similarity-annotator/media:/media/
      - /mnt/asplab-web/asplab-shared/similarity-annotator/tmp:/tmp/
    command: uwsgi uwsgi.ini
    dns: 84.89.128.11
