version: '2'
services:
  db:
    image: postgres

  gearman:
    image: kendu/gearman

  gearman-worker:
    build: .
    command: python manage.py gm_worker_processing
    volumes_from:
      - web
    depends_on:
      - gearman

  web:
    build: .
    ports:
      - 8000:8000
    environment:
     DEPLOY_ENV: "dev"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - ./media:/media/
      - ./tmp:/tmp/
    depends_on:
      - db
