version: '2'
services:
 db:
  image: postgres
 gearman:
  image: kendu/gearman
 gearman-worker:
  build: .
  command: python manage.py gm_worker_processing
  depends_on:
    - gearman
  volumes_from:
   - web
 web:
  build: .
  command: python manage.py runserver 0.0.0.0:8000
  ports:
   - "8000:8000"
  depends_on:
   - db

