version: '2'
services:
  db:
    image: postgres

  gearman:
    extends:
      file: ./docker-compose.common.yml
      service: gearman

  gearman-worker:
    extends:
      file: ./docker-compose.common.yml
      service: gearman-worker
    volumes_from:
      - web
    depends_on:
      - gearman

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - ./media:/media/
      - ./tmp:/tmp/
    depends_on:
      - db
